### PR TITLE
Add plot recipes for `PEtabOptimisationResult`

### PR DESCRIPTION
**Pull request by TorkelE**
Adds plot recipes for `PEtabOptimisationResult` and `PEtabMultistartOptimisationResult`. These are added in an extension that is loaded if `Plots` is loaded.

Demo:
```julia
# Create petab problem

using Catalyst
using PEtab

rn = @reaction_network begin
    kB, S + E --> SE
    kD, SE --> S + E
    kP, SE --> P + E
end

u0 = [:S => 1.0, :E => 1.0, :SE => 1.0, :P => 0.0]
p_true = [:kB => 1.0, :kD => 0.1, :kP => 0.8]

state_map = [:E => 1.0, :P => 0.0]
parameter_map = [:c1 => 1.0]

using OrdinaryDiffEq, Random
sol = solve(ODEProblem(rn, u0, (0.0, 10.0), p_true), Tsit5(); saveat=0.1)
data = (0.8 .+ 0.4*rand(10)) .* sol[4,10:10:end]

obss = let 
    @unpack P = rn
    obs_P = PEtabObservable(P, 0.5, transformation=:lin)
    Dict("obs_P" => obs_P)
end


_kB = PEtabParameter(:kB, lb=1e-3, ub=1e3, scale=:log10)
_kD = PEtabParameter(:kD, lb=1e-3, ub=1e3, scale=:log10)
_kP = PEtabParameter(:kP, lb=1e-3, ub=1e3, scale=:log10)
_parameters = [_kB, _kD, _kP]

conditions_1 = Dict()
conditions = Dict("c1" => conditions_1)

using DataFrames
measurements = DataFrame(simulation_id=fill("c1", 10), obs_id=fill("obs_P", 10), time=sol.t[10:10:end], measurement=data)

petab_model = PEtabModel(rn, conditions, obss, measurements, _parameters, state_map=u0, parameter_map=p_true)
petab_problem = PEtabODEProblem(petab_model)
```
```julia
# fit paraemters.
using Optim
res = calibrate_model(petab_problem, rand(3), IPNewton(), options=Optim.Options(iterations = 200), save_trace=true)
res_ms = calibrate_model_multistart(petab_problem, IPNewton(), 5, nothing, options=Optim.Options(iterations = 200), save_trace=true)
``` 

The plot simply plots the objective function values across all evaluations of the optimizer. An argument (`plot_type`) designates whenever to plot the objective function value (as scatter points, when `objective` is used), or the best value so far in the optimization (default, as a line plot, when  `best_objective` is used). Examples:
```julia
plot(res)
```
image

```julia
plot(res; plot_type=:objective)
```
image

```julia
plot(res_ms)
```
image

```julia
plot(res_ms; plot_type=:objective)
```
image

Currently, there are neither tests nor documentation, but if something like this looks good I am happy to write. There are also opportunity to decide on default plotting attributes.

### CODE REVIEW

**Comment by sebapersson** [comment]
A plots extension would be great, especially for the multistart optimization. 

When doing parameter estimation besides the trace-plots you currently have implemented, other plots like waterfall plots are usually useful. Do you think something like this could work (if it was not what you were thinking?);

```julia
plot(res_ms; plot_type=:waterfall)
```

As for attributes, at least theme-wise I like [wong](https://docs.juliaplots.org/latest/generated/plotthemes/#:wong) as it employs great color-palettes.

**Comment by TorkelE** [comment]
I have added waterfall plot capacity:
```
plot(res_ms; plot_type=:waterfall)
```
image

For this, labels are currently turned off, and colours are different for different dots. Ideally these plots should probably also contain some good way to group the dots by colour though? I am trying to figure out the best way to do it.

Regarding setting the theme to e.g. `:wong`. I talked to the Extension expert in the group, and he said that this would require making the setting depend on PlotThemes (since it would need to load it), which would mean it is only activated if the user runs both
```
using Plots
using PlotThemes
```
which seems excessive. Maybe let's just have it by default, and if users want to switch they can run
```
using PlotThemes
theme(:wong)
```
themselves.

Finally, the extension expert guy also said that it is better to call extensions stuff like `PEtabPlotsExtension`. The reason is that if two packages both have extensions `PlotsExtension` this can cause trouble. I renamed the `PlotsExtensions` according to this standard, but it would probably make sense to do similar for the remaining ones?

**Comment by sebapersson** [comment]
Then I say we keep the default theme, and the naming sounds good!

For waterfall plots I know that some software uses a palette like viridis (on log-scale) where they map the color to the value, to make lower values yellow, and higher values dark purple. I think [cividis](https://github.com/marcosci/cividis) might be a better palette for something like this (the palette is also perceptually uniform so it can make sense to color after it), what do you think? Also does the waterfall plot and the other plots somehow handle Inf values? For harder models some optmisation starts usually fail, and for these we typically return Inf. 

In addition to a waterfall plot for multistart optimisation I think the following plots would be useful:

1. A parameter plot as you showed in #64
2. A plot of fmin vs runtime (it can be really useful to see how long time it takes to reach the optima). 

If you come up with any additional plots feel free to add.

**Comment by TorkelE** [comment]
Yes, those additional plots are good, I will add them as well. 

For the waterfall plot, I am meaning to have distinct colours and labels for each dot (slightly complicated, surprisingly, but fix on the way). Ideally, people then provide annotation for the various endpoints to group them, like this one:
image
Adding a colour scale which is equivalent to the y-axis (is that what you meant they do?) seems better than having them all the same colour, but not sure if it is ideal (although other packages probably know what they are doing). One alternative is to attempt to run a clustering on the end points in the waterfall plots, colouring dots considered "the same" in identical colours. However, this is definitely non-trivial.

Good you brought up Infs, totally forgot. I have previously handled them this ways:
1) Remove these from the plots entirely.
2) Artificialy change their value to the highest non-inf value in the evaluation.
3) Artificialy change their value to the highest non-inf value in the evaluation, and then plot them using a different marker (e.g. an "x" instead of an "o").
I'm leaning towards 3. Should work for all scatter-type plots, and where lines are used they are kind of ignored by default.

**Comment by sebapersson** [comment]
Now I see what you mean with the color, and it would be great to color according to local optima (better than my idea). 

Something that might help with the coloring is that we usually use 0.1 as threshold. So if a value is  <0.1 from the global optima we consider it to have converged to the global optima. Given this, one can start from the lowest value use the 0.1 to cluster the global optima, then move on the lowest value not in the global cluster, create new cluster within <0.1 (and so on).

For Inf I also think 3 is the best - as it will clearly show the number of failed runs.

**Comment by TorkelE** [comment]
I will use solution (3) then.

For the colors, if you already have a threshold, that is useful (and I could make this a kwarg for those who want to use it). 

This threshold, is it in parameter space or for objective function value? If for the objective function value the clustering doesn't necessarily provide more information than what is already in the plot. However, if in parameter space, two end points in different local minimums (but with similar objective values) would be coloured differently, which might be useful to know. If the threshold is here, how does it scale with dimensions (e.g. is it just the norm between two points)?

**Comment by sebapersson** [comment]
The threshold is for the objective value, and I agree it does not provide much more information for the waterfall plot. But, if you keep the coloring for the parameter as in #64 I think it will be easier to see if the same optima was reached.  It would also be interesting to the clustering in parameter space, but that is I think a drastically harder problem (multi-dimensional clustering is never easy)

**Comment by TorkelE** [comment]
Sounds good. I colour according to this kind of clustering (in both these two types of plots), and the user can override this if they want to.

Given some of these more fancy versions, it would be useful to have better (than I am currently using) problems(/outputs) to check the plots on. If you happen to have problems on hand where:
1) Some objective function evaluations are Inf.
2) Several different local optima are reached.
that would be useful

**Comment by TorkelE** [comment]
Great! Thanks a lot :)

**Comment by TorkelE** [comment]
If you have the workflow I could copy it and run it locally, but if you have the already and can just send serialized versions of the output struct that would be awsome.

**Comment by sebapersson** [comment]
This is the workflow:

```julia
using PEtab
using PyCall                      
using OrdinaryDiffEq      
path_yaml = joinpath(@__DIR__, "Boehm", "Boehm_JProteomeRes2014.yaml") # @__DIR__ = file directory
petab_problem = PEtabODEProblem(PEtabModel(path_yaml, verbose=true))
dir_save = joinpath(@__DIR__, "Boehm_opt")
res1 = calibrate_model_multistart(petab_problem, Fides(nothing; verbose=false), 1000, dir_save, seed=123)

path_yaml = joinpath(@__DIR__, "..", "test", "Test_ll", "Crauste_CellSystems2017", "Crauste_CellSystems2017.yaml") # @__DIR__ = file directory
petab_problem = PEtabODEProblem(PEtabModel(path_yaml, verbose=false), 
                                ode_solver=ODESolver(QNDF()))
dir_save = joinpath(@__DIR__, "Crauste_opt")                                
res2 = calibrate_model_multistart(petab_problem, Fides(:BFGS; verbose=true), 1000, dir_save, seed=123) 
```

To get good curves to test on I have to run 1000 multistarts. You can run it if you want (note that Fides works best here), otherwise tomorrow morning (Swedish time) I will compile together the results and send output struct to you (I want to run the code regardless for testing purposes) :). 

Note to run it you also need the [Boehm](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/master/Benchmark-Models/Boehm_JProteomeRes2014) and [Crauste](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/master/Benchmark-Models/Crauste_CellSystems2017) PEtab-folders.

**Comment by sebapersson** [comment]
To read optimisation results you can use this in progress util function:

```julia
function read_optimisation_results(dir_save::String; which_run::String="1")::PEtabMultistartOptimisationResult
    
    @assert isdir(dir_save) "Directory $dir_save does not exist"
    
    data_res = CSV.read(joinpath(dir_save, "Optimisation_results" * which_run * ".csv"), DataFrame)
    data_parameters = CSV.read(joinpath(dir_save, "Best_parameters" * which_run * ".csv"), DataFrame)
    data_startguess = CSV.read(joinpath(dir_save, "Start_guesses" * which_run * ".csv"), DataFrame)

    _runs = Vector{PEtab.PEtabOptimisationResult}(undef, size(data_res)[1])
    for i in eachindex(_runs)
        _runs[i] = PEtab.PEtabOptimisationResult(Symbol(data_res[i, :alg]), 
                                                Vector{Vector{Float64}}(undef, 0),
                                                Vector{Float64}(undef, 0),
                                                data_res[i, :n_iterations],
                                                data_res[i, :fmin],
                                                data_startguess[i, 1:end-1] |> Vector{Float64},
                                                data_parameters[i, 1:end-1] |> Vector{Float64},
                                                data_res[i, :converged], 
                                                data_res[i, :run_time])
    end
    run_best = _runs[argmin([isnan(_runs[i].fmin) ? Inf : _runs[i].fmin for i in eachindex(_runs)])]
    _res = PEtabMultistartOptimisationResult(run_best.xmin,
                                            run_best.fmin,
                                            length(_runs),
                                            run_best.alg,
                                            "",
                                            dir_save,
                                            _runs)
    return _res
end
```

I will send you the directories with the results.

**Comment by TorkelE** [comment]
I've updated, all 5 types of plots discussed are now possible. Currently, I group runs as discussed, and then give runs in the same group the same colour. I have labels off. I have tried to make guesses for stuff like `lw`, `la`, `ms`, `ma` that might make sense for that type of plot (which can then be adjusted by the user). If we had parameter names (which we don't) we could have added them to the parallel coordinates plot, however, I am not sure if it is actually needed for its desired purpose.

Here for the Boehm model (10 multistarts):

Objective function evaluations `plot(res_ms; plot_type = :objective)`
image

Best objective function evaluations `plot(res_ms; plot_type = :best_objective)` (default)
image

Waterfall `plot(res_ms; plot_type = :waterfall)`
image

Runtime v objective function evaluations`plot(res_ms; plot_type = :runtime_eval)`
image

Parallel coordinates `plot(res_ms; plot_type = :parallel_coordinates)`
image

And here are the same for the Crauste model (also 10 multistarts)
image
image
image
image
image

None of my runs actually generated Inf values, but here is a Boehm model with 5 multiruns where I manually set a few values to Inf:
image

It also works for single calibration runs (not multistart):
```julia
plot(res_sing_boehm)
```
image

```julia
plot(res_sing_boehm; plot_type = :objective)
```
image

**Comment by TorkelE** [comment]
Any more things? Some of the multistart plots gets quite crowded. Maybe there should be an `idxs` argument to sub-sample. E.g. if there are 100 multistarts and you set `idxs=1:10` only the first 10 are used for the plot.

**Comment by sebapersson** [comment]
Allowing subsampling sounds good for multistart, and with `idxs=1:10` I think it would be best to then extract the 10 best runs etc. Happy to see the plots taking shape!

Some minor notes;
1. For the runtime plot add units [s] (runtime always measured in seconds)
2. When optimization fails actually `Inf` is not returned, rather `NaN` (do not know if this is considered)
3. I think the parallel coordinate plot should have parameter names (with parameter names on the y-axis to make it easy to read the visual). Not making the name accessible is a mistake on my part but they should now on the Catalyst_integration branch be available under `res.xnames`

**Comment by TorkelE** [comment]
1) Will do.

2) Not handled, but I will treat these as Inf (alternatively I could give `NaN`s "+" markers and `Inf` "x" markers?).

3) I flipped the axises (so parameters was on the x axis) since I predicted plots more commonly to be "long" than "high", and as parameters increase you'd want more "resolution" that way. Happy to flip in back though.
With the `res.xnames` I will add these to the axis label. For DiffEq I think the solutions generally contain the problem that was solved, and I was thinking of suggesting something similar here (then e.g. when the fitted parameters/initial conditions are retrieved, the petab problem would not have to be supplied). However, in this case the PEtab problems are really large structures right? In which case it might not make sense to add them there.

If

**Comment by sebapersson** [comment]
2. I think you should handle them as Inf (in case of NaN or Inf something has gone bad with the parameter estimation). 
3. The `PEtabODEProblem` is really large so I think adding them might not be ideal (they especially get large for larger models). And I think flipping the plot is the best idea, as if the text is on the x-axis it becomes hard to read the label (it is recommended in this book which I find an excellent reference on visualization https://clauswilke.com/dataviz/visualizing-amounts.html#dot-plots-and-heatmaps.

And a default of 10 sounds good!

**Comment by TorkelE** [comment]
Sounds good, and thanks for the link, will have a look

**Comment by TorkelE** [comment]
I have made another update:

I have added the following argument to the `plot` command:
- `clustering_function`: A function that takes the `runs` field and returns the clustering colours. Currently, nothing is changed as this defaults to the same `assign_grouped_colors` function we have previously used. However, if we or someone else want to make their own more advanced clustering functions, this makes it easy to use that one instead.
- `idxs`: The indexes of the runs in the `runs` vector to use for plotting. defaults to `best_runs(res_ms, best_idxs_n)` which extracts the `best_idxs_n` best runs.
- `best_idxs_n`: if the default `best_runs` function is used to decide which runs to display, this permits tuning this number. Defaults to `plot_type in [:waterfall, :runtime_eval] ?  res_ms.n_multistarts : 10` (that is 10, unless the `waterfall` or `runtime_eval` plot types are used, in which case all runs are shown.

`NaN`s and `Inf`s are now treated identically.

I have updated the parallel coordinates plot as discussed, here is a new version:
image

**Comment by TorkelE** [comment]
There were some technicalities with this depending on the latest catalyst integration branch. Thing works locally, but I will wait to push the remaining changes until that got merged.

**Comment by sebapersson** [comment]
All this sounds really good, and I like how the parallel coordinate plot turned out with the parameters on the y-axis. I have now also merged the latest Catalyst integration branch with main

**Comment by TorkelE** [comment]
Ok, hopefully this should be properly synched with the main branch now.

**Comment by sebapersson** [comment]
I am happy with the current plot syntax, and everything looks good to me (also runs locally).

Small notes:
1. For mutlistart optmisation I think the waterfall plot should be the default
2. For trace plots it should only be objective-value on the y-axis.

Besides this, the only thing left is documentation and, and tests (even though I am not entirely sure how to test the code for plots).

If you could add tests checking the code can run, and maybe that the values appear in the correct order for the waterfall plot, I would be happy to merge this PR. If you could add some documentation would also be great (otherwise I can do it). 

Time-wise I would like to have this functionality before releasing PEtab 2.0 (which I plan to to on Wednesday)

**Comment by sebapersson** [comment]
The approach for the docs sounds good. 

And thanks for asking on the testing part

**Comment by TorkelE** [comment]
Actually, regarding
`For trace plots it should only be objective-value on the y-axis.`
My intention was that for 
image
each dot is the f evaluation in that iteration (objective value)
and for 
image
I instead plot the best f evaluation up until that point.

So the first case is not necessarily a strictly decreasing function (although in these cases that is the case, but for some combination of problem+optimiser maybe not). The second case would be a decreasing function. Hence the difference in names. Or am I missing something here, or PEtab doing parts of this by default?

**Comment by TorkelE** [comment]
Seems master somehow had built on and gotten some of this PR? Either case,  rebased this on master and it turned out really messy. It should be good now though.

**Comment by TorkelE** [comment]
Tests and documentation added

**Comment by sebapersson** [comment]
`For trace plots it should only be objective-value on the y-axis.`
I just meant that the y-label should be objective value all the time, but I now see what you mean, and I think it works!

**Review by sebapersson — APPROVED** [review]
I am happy with this, all functionality is in place, with documentation and tests. 

Will try merge.

**Comment by sebapersson** [comment]
Do the plotting test pass locally?

(they fail in the CI test)

**Comment by sebapersson** [comment]
The test fails because with `idx` you want to plot results for run `1:25`. However with  

```julia
petab_ms_res = PEtabMultistartOptimisationResult(joinpath(@__DIR__, "Optimisation_results", "boehm"))
```

you only read the results from the optmisation that ends with `1` (e.g you only read Parameters1.csv file, not all csv files with all numerical indices). Now run `1` only have 7 startguesses (or rather 7 runs), therefore you cannot plot run `1:25`. 

The way to fix the error would be to re-generate the data for run `1` with at least 25 runs, also in case `idx` as here exceeds the number of runs it would be good to throw an error.

Could you fix this?

**Comment by TorkelE** [comment]
I tried to run `]test` locally, but it get stuck. I left it running over night but it is still at
```
...
  [83775a58] Zlib_jll v1.2.13+1 `@stdlib/Zlib_jll`
  [8e850b90] libblastrampoline_jll v5.8.0+1 `@stdlib/libblastrampoline_jll`
  [8e850ede] nghttp2_jll v1.52.0+1 `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll v17.4.0+2 `@stdlib/p7zip_jll`
        Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ are restricted by compatibility constraints from upgrading.
Precompiling project...
  Progress [>                                        ]  0/2
  ◐ PEtab → SciMLSensitivityExtension
  ◒ PEtab → ZygoteExtension
```

I ran through the tests in a normal file, but that was in the same file I generated the `PEtabMultistartOptimisationResult` output, hence I didn't catch it. Thanks for debugging out the error, don't think I would have caught it that easily. An update will be up soon.

**Comment by sebapersson** [comment]
Yes, each time you run 

```julia
calibrate_model_multistart(petab_problem_boehm, IPNewton(), n1, "boehm"; options=Optim.Options(iterations = n2), save_trace=true) 
```

you create new files with `n1` optimization results. The reason I made it like this is because I do not want to append to already existing runs (so user can tell runs apart), and I would not like to delete runs either. You can also already select which one to read;

```julia
petab_ms_res = PEtabMultistartOptimisationResult(joinpath(@__DIR__, "Optimisation_results", "boehm"), which_run="5")
```
loads run 5. This is a bit involved, and down the line it is probably worth to look into a better interface.

**Comment by TorkelE** [comment]
No, I think this approach seems quite ideal. I agree the runs should be kept apart, and overriding previously existing results (as I naively thought might be the case) seems bad. The `which_run` argument also seems just what is needed.

**Comment by sebapersson** [comment]
It now fails on:

`SystemError: opening file "/home/runner/work/PEtab.jl/PEtab.jl/test/Plot_optimisation_results.jl": No such file or directory`

Have you renamed the file?

**Comment by TorkelE** [comment]
fix pushed

**Comment by sebapersson** [comment]
Happy to have this merged, thanks for adding plotting capability!

**Pull request merged**
