### PR TITLE
Add ability to extract model parameters for simulation

### PR DESCRIPTION
**Pull request by sebapersson**
See #85 

The new function can cover pre-eq (by unfortunately having to rerun the pre-eq simulation but there is no way around), and model with condition specific parameters. Moreover, either a map or vector can be returned via `retmap`. 

The function is tested.

I am struggling a bit with finding a good name. Feedback appreciated @TorkelE. 

When all looks good I can improve docstring and merge with main.

### CODE REVIEW

**Comment by TorkelE** [comment]
Maybe something like get_model_fit or get fitted_model. get_fitted_u0_ps is descriptive (but not very pretty) 

Would it be possible to make two sub functions, appending _ps and _u0 (extracting just those parts of the fit.

**Comment by sebapersson** [comment]
You are thinking two functions:

```julia
get_fitted_ps
get_fitted_u0
```

I like this solution the best as what the functions do is clear, and then the user will not have to confused whether the function returns u0 or p as first argument. It will also be easy to code.

If you do not have any objection I will go with this.

We can probably also provide the user with a function named `get_fitted_ode` (or similar) returning an ODE problem with ps and u0 correctly placed.

**Comment by TorkelE** [comment]
Sounds good. Actually, the get_fitted_ode returning the full ODE Problem sounds like a really good idea. That should totally get implemented at some point.

**Comment by TorkelE** [comment]
Looks good. 

Maybe, give that condition_id can be optional (if only 1 condition is used), I'd consider making it an arg, with default value equal to the default condition name.

**Comment by sebapersson** [comment]
I agree, I have now added this. To also handle models with a single specified simulation condition if `condition_id=nothing` it now defaults to the first simulation condition.

**Pull request merged**
